server:
  port: 8081

spring:
  application:
    name: learning-platform-auth
 

  datasource:
    url:  jdbc:postgresql://localhost:5432/learning_platform_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath*:db/migrations/master-migration.xml
  jpa:
    show-sql: true

logging:
  level:
    root: info
jwt:
  expiration: 3600
  secret: "GibVa0MF2Wg29IVvY+kRFDf3xG6GVog9V5UocoUab6s="


encryption-key: "e0ec288d28ef0b99d9df6bb51abe59fca34d276d8f9f170e3853c3db216ff085f"



