# Path to the main changelog file
changeLogFile=db/migrations/master-migration.xml

# JDBC driver class
driver=org.postgresql.Driver

# JDBC URL for your database
url=jdbc:postgresql://localhost:5432/learning_platform_auth

# Database credentials
username=postgres
password=postgres

# Path to JDBC driver (needed if running Liquibase CLI)
# classpath=./path/to/jdbc/driver.jar

# Logging level (info, warning, severe, debug)
logLevel=info

# (Optional) Schema Liquibase uses for tracking
# liquibaseSchemaName=LIQUIBASE

# (Optional) Default schema for changes
# defaultSchemaName=PUBLIC

# (Optional) Contexts to control which changesets run
# contexts=dev,prod

# (Optional) Labels to control which changesets run
# labels=feature-x

# (Optional) File to write SQL output to (for updateSQL command)
# outputFile=liquibase-output.sql


# mvn liquibase:update -Dliquibase.propertyFile=src/main/resources/db/migrations/liquibase.properties